### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by phr34k0** [TobinShields/Zaqar_EmailSpoofer#1]
I have sendmail, apache2, php, mysql all setup but this doesn't work. Sendmail and PHPMAIL is working on my server except for your script

![image](https://user-images.githubusercontent.com/13272249/45029700-2059f600-b07c-11e8-81ac-a59cb7ff3759.png)

**Comment by TobinShields** [comment]
Hey there--strange, I am getting the same error. I wonder what happened? I am going to experiment with this a little more, but in the meantime I am going to rollback to v1.2 as I know it works.

**Comment by phr34k0** [comment]
I got it working. Haha.
