### ISSUE TITLE
Email sending fails

### ISSUE THREAD

**Issue by thesowmik** [TobinShields/Zaqar_EmailSpoofer#10]
The mailer.php returns success message, but I/others didn't got the spoofed mails even in the spam box! Hope you will give me a solution or update your script!

**Comment by NotEneas** [comment]
try to look into spam folder... working for me.

**Comment by TobinShields** [comment]
> The mailer.php returns success message, but I/others didn't got the spoofed mails even in the spam box! Hope you will give me a solution or update your script!

Who are you hosting with? Sometimes hosting providers are marked as SPAM and blacklisted. So you should be using a well respecting hosting platform to best ensure your email get through

**Comment by jasonsmithh22** [comment]
> 

how did you configure your smtp server?
