### ISSUE TITLE
email not sent

### ISSUE THREAD

**Issue by barrredemption7** [TobinShields/Zaqar_EmailSpoofer#13]
> Awe Snap! Your message was not sent. Something went wrong with the PHP mail() function and is returning a value of FALSE. Chances are if you are seeing this message it means that it could not reach out to the SMTP server. Make sure that the webserver you are running is configured to also point to a mail server, 

this is the error message i get when sending out email, i make us of namecheap hosting, they have mail enabled by default, please help me out.

**Comment by TobinShields** [comment]
I have never used this service--are you sure they enable SMTP by default?

**Comment by barrredemption7** [comment]
yes, i contacted the hosting support team, they said yes, can you recommend another hosting that works perfectly with your script?

**Comment by TobinShields** [comment]
I have confirmed that it works with GoDaddy.com

**Comment by rushdeals101** [comment]
How does one add new smtp like sendinblue smtp ?

**Comment by TIN2539** [comment]
I used 000webhost - no problem, but all emails go to spam
Now I try create it in bluehost, but nothing work. Can anybody help?
