### ISSUE TITLE
Pointing to SMTP 

### ISSUE THREAD

**Issue by TobinShields** [TobinShields/Zaqar_EmailSpoofer#14]
am having same issue although my namecheap hosting has smtp enabled automatically on the server, can you show me how to setup the smtp to point/link directly to the spoofer script?

_Originally posted by @barrredemption7 in https://github.com/TobinShields/Zaqar_EmailSpoofer/issues/4#issuecomment-850922752_

**Comment by nnnnnnnnnrrr3** [comment]
yeah same thing happened to me
