### ISSUE TITLE
error sending mails 

### ISSUE THREAD

**Issue by lacosted** [TobinShields/Zaqar_EmailSpoofer#2]
i always get the following error 
"Awe Snap! Your message was not sent. Something went wrong with the PHP mail() function and is returning a value of FALSE. Chances are if you are seeing this message it means that it could not reach out to the SMTP server. Make sure that the webserver you are running is configured to also point to a mail server."   
when trying to send mail what how could i overcome this smtp poining.

**Comment by TobinShields** [comment]
Hey--not sure. This program is designed to work seamlessly on a server that already has PHP and SMTP enabled and working. What are you currently running the app on?

**Comment by Donas01** [comment]
Hi, 
i Have the same issue, i'm using a local provider using the cpanel and the server has already php&smtp enabled.

**Comment by Jeffkoopa** [comment]
I had what i think is the same problem,
it failed when sending emails without an attachment. using _smtp-relay.sendinblue.com_
changed line 77 in mailer.php 
from:

>    $mail->addAttachment($path);         // Add attachments

to:

>     if (!empty($fileTempName)) { //checks to see if a file was attatched
>         $mail->addAttachment($path);         // Add attachments
>     }

then it worked

**Comment by wioxjk** [comment]
> I had what i think is the same problem,
> it failed when sending emails without an attachment. using _smtp-relay.sendinblue.com_
> changed line 77 in mailer.php
> from:
> 
> > $mail->addAttachment($path);         // Add attachments
> 
> to:
> 
> > ```
> > if (!empty($fileTempName)) { //checks to see if a file was attatched
> >     $mail->addAttachment($path);         // Add attachments
> > }
> > ```
> 
> then it worked

Thanks, this solved it! I had the same problem.

**Comment by zeliserzz** [comment]
And how to make sure that letters do not end up in spam?)
