### ISSUE TITLE
Error sending emails to Cc and Bcc addresses

### ISSUE THREAD

**Issue by bhimbolar** [TobinShields/Zaqar_EmailSpoofer#5]
I can send emails to primary email addresses successfully, but emails fail whenever i include Cc or Bcc addresses. It gives the following error:
"Awe Snap! Your message was not sent. Something went wrong with the PHP mail() function and is returning a value of FALSE. Chances are if you are seeing this message it means that it could not reach out to the SMTP server. Make sure that the webserver you are running is configured to also point to a mail server."

**Comment by TobinShields** [comment]
@bhimbolar--I just attempted to recreate this issue and I was able to send with both BCC and CC, and also just CC. Not sure what the issue is on your end? I have tested this with godaddy.com
