### ISSUE TITLE
Compatible with Termux or Nethunter?

### ISSUE THREAD

**Issue by Vardaan79** [TobinShields/Zaqar_EmailSpoofer#6]
Can this be used in Kali Nethunter(rooted). If yes, then HOW?

Looking forward for your response.

**Comment by TobinShields** [comment]
Great question! You need to have access to a public SMTP mail server. So the short answer is that there is no good way to have this 'self hosted' inside Kali, unless you installed and configured a whole mail server inside Kali, which isn't really its purpose. This requires hosted infrastructure outside of just an attacking machine.
